name: Build Ubuntu Focal armhf Rootfs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          chmod +x ./build-rootfs.sh
          ./build-rootfs.sh
