name: Build rootfs_12.img

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Grant execute permission
        run: chmod +x ./build-rootfs12.sh

      - name: Build rootfs image
        run: ./build-rootfs12.sh

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v6  # 由 v5 改为 v6
        with:
          name: rootfs_128m
          path: build/rootfs_12.img
          retention-days: 3
